// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalcCropForAspect(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Record<string, number>>;

export function CancelOperation():Promise<void>;

export function CheckFFmpeg():Promise<main.FFmpegStatus>;

export function GetFrame(arg1:string,arg2:number,arg3:string):Promise<string>;

export function LoadFiles(arg1:string):Promise<Array<main.VideoInfo>>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function StartDetection(arg1:number):Promise<void>;

export function StartProcessing(arg1:main.EncodeSettings):Promise<void>;

export function UpdateCrop(arg1:string,arg2:string):Promise<boolean>;
