// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalcCropForAspect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CalcCropForAspect'](arg1, arg2, arg3, arg4);
}

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function GetFrame(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFrame'](arg1, arg2, arg3);
}

export function LoadFiles(arg1) {
  return window['go']['main']['App']['LoadFiles'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function StartDetection(arg1) {
  return window['go']['main']['App']['StartDetection'](arg1);
}

export function StartProcessing(arg1) {
  return window['go']['main']['App']['StartProcessing'](arg1);
}

export function UpdateCrop(arg1, arg2) {
  return window['go']['main']['App']['UpdateCrop'](arg1, arg2);
}
